// try {
//     let num = 10;
//     let result = num / qwdffdw; 
//     console.log("Result:", result);
//   } catch (error) {
//     console.log("An error occurred:", error.message);
//   }

try {
    console.log(age); // Age is not defined but still the code gets executed
} catch(err){
    console.log(err.name)
    console.log(err.message)
}

const a= 2*4;
console.log(a);  